spring:
  application:
    name: API
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/ADT-Validation-documents
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  config:
    import: "configserver:http://localhost:8788"
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: Administration
          uri: lb://ADMINISTRATION
          predicates:
            - Path=/users/**,/ADTConst/**,/clients/**
        - id: documentValidation
          uri: lb://documentValidation
          predicates:
            - Path=/documentValidation/**

server:
  port: 8282
  servlet:
    context-path: /

# Configuration pour Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
app:
  key_cloak:
    realm: ADT-Validation-documents
    baseUrl: http://localhost:8000
    auth: ${app.key_cloak.baseUrl}/auth/realms/${app.key_cloak.realm}/protocol/openid-connect/token
    ClientDetails: http://localhost:8282/clients/details/app/
    logout: ${app.key_cloak.baseUrl}/auth/realms/${app.key_cloak.realm}/protocol/openid-connect/logout
    client_id: microservice-administration
    client_secret: 36088666-047f-44d6-a1d4-8a8370a704db
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: swagger-ui/index.html
    operationsSorter: method
  